; Role modulu testi (ESP32-S3 Super Mini). 220V BAGLAMADAN, sadece rolenin "tik" sesiyle dene.
[env:esp32s3-supermini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_qspi
board_upload.flash_size = 4MB
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
