; Masa lambasi dugumu / hub - ESP32-S3 Super Mini
; Kapasitif dokunma + role + ESP-NOW (HomeSpan'in SpanPoint'i). WiFi'ye/modeme baglanmaz.
[env:esp32s3-supermini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_qspi
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = huge_app.csv
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I../shared
lib_deps = homespan/HomeSpan@^2.1.8
